.\" -------- fancyquote(1) --------
.TH FANCYQUOTE 1 "2025-08-29" "fancyquote 0.1"
.SH NAME
fancyquote \- display a centered quote in the terminal
.SH DESCRIPTION
.B fancyquote
prints a centered quote using ncurses and runs until interrupted (with any key press)
.SH OPTIONS
No options support yet
.SH EXIT STATUS
0 on success, non-zero on error.
.SH EXAMPLES
fancyquote "O Hello There"
.fi
.SH AUTHORS
Written by sys-deamon on GitHub
.SH BUGS
Report at https://github.com/sys-deamon/fancy-quote